Repository hacs/integration, pull requests merged in 2019-10, with the labels that each got.

#579 Add YouLess component
  repositories/integration
Labels: New default repository

#580 Add Kostal Piko sensor
  repositories/integration
Labels: New default repository

#581 Add buienalarm sensor
  repositories/integration
Labels: New default repository

#582 Dutch translation
  custom_components/hacs/.translations/nl.json
Labels: Translation

#578 Frontend reboot
  .devcontainer/devcontainer.json
  .devcontainer/sample_configuration.yaml
  .eslintrc.yaml
  .gitignore
  custom_components/hacs/.translations/en.json
  custom_components/hacs/__init__.py
  custom_components/hacs/config_flow.py
  custom_components/hacs/frontend/__init__.py
  custom_components/hacs/frontend/experimental/main.js.gz
  custom_components/hacs/hacsbase/__init__.py
  custom_components/hacs/hacsbase/configuration.py
  custom_components/hacs/http.py
  custom_components/hacs/repositories/integration.py
  custom_components/hacs/repositories/repository.py
  custom_components/hacs/ws_api.py
  custom_components/hacs/ws_api_handlers.py
  docs/installation/configuration.md
  package-lock.json
  package.json
  rollup.config.js
  src/main.ts
  src/misc/Authors.ts
  src/misc/CustomRepositories.ts
  src/misc/LoadLovelace.js
  src/misc/LoveLaceHint.ts
  src/misc/RepositoryNote.ts
  src/misc/ScrollToTarget.ts
  src/misc/navigate.ts
  src/panels/corePanel.ts
  src/panels/repository.ts
  src/panels/settings.ts
  src/style/ha-style.ts
  src/style/hacs-style.ts
  src/style/nav-style.ts
  src/types.ts
  tsconfig.json
Labels: Backend, Documentation, Frontend

#584 Fix dir download issue
  .eslintrc.yaml
  custom_components/custom_components
  custom_components/hacs/.translations/en.json
  custom_components/hacs/.translations/es.json
  custom_components/hacs/.translations/fr.json
  custom_components/hacs/.translations/nl.json
  custom_components/hacs/repositories/manifest.py
  custom_components/hacs/repositories/repository.py
  src/main.ts
  src/misc/Authors.ts
  src/misc/CustomRepositories.ts
  src/misc/LoveLaceHint.ts
  src/misc/RepositoryNote.ts
  src/types.ts
Labels: Backend

#586 Fix some typos on Spanish Translation
  custom_components/hacs/.translations/es.json
Labels: Translation

#588 no.json
  custom_components/hacs/.translations/no.json
Labels: Translation

#589 Add german translation
  custom_components/hacs/.translations/de.json
Labels: Translation

#590 Remove deprecated plugin lovelace-markdown-mod
  repositories/plugin
Labels: New default repository

#600 Link to Configuration in Step 8 - Fixed
  docs/installation/manual.md
Labels: Documentation

#606 Updated Spanish Translation
  custom_components/hacs/.translations/es.json
Labels: Translation

#604 More typos
  custom_components/hacs/.translations/no.json
Labels: Translation

#607 Update Spanish Translation
  custom_components/hacs/.translations/es.json
Labels: Translation

#611 Fix spinners
  .gitignore
  custom_components/hacs/const.py
  custom_components/hacs/strings.json
  src/panels/repository.ts
  src/panels/settings.ts
Labels: Backend

#614 Remove duplicate repository structure description
  docs/developer/integration.md
Labels: Documentation

#617 Updated incorrect links in documentation
  docs/installation/manual.md
  docs/installation/terminal.md
Labels: Documentation

#619 New Integration - Minecraft Version Checker
  repositories/integration
Labels: New default repository

#583 Update plugin
  repositories/plugin
Labels: New default repository

#575 Added lightwave2 repository
  repositories/integration
Labels: New default repository

#633 Added Mitsubishi ECHONET Custom Component to HACS.
  repositories/integration
Labels: New default repository

#636 tmp path from tempfile
  custom_components/hacs/hacsbase/backup.py
  custom_components/hacs/repositories/repository.py
Labels: Backend

#644 Adding ElkoEP Lara integration
  repositories/integration
Labels: New default repository

#645 Blacklist here_travel_time
  repositories/blacklist
Labels: New default repository

#647 Add SamsungTV Custom integration
  repositories/integration
Labels: New default repository

#648 Add gui-sandbox
  repositories/plugin
Labels: New default repository

#649 LGTM Fixes
  custom_components/hacs/ws_api_handlers.py
  src/panels/corePanel.ts
Labels: Backend

#666 Fixed typo
  documentation/content/installation/manual.md
Labels: Documentation

#667 Fixed typo
  documentation/content/installation/remove.md
Labels: Documentation

#668 Fixed typo
  documentation/content/configuration/legacy.md
Labels: Documentation

#669 Fixed typo
  documentation/content/categories/appdaemon_apps.md
Labels: Documentation

#670 Fixed typo
  documentation/content/categories/python_scripts.md
Labels: Documentation

#671 Fixed typo
  documentation/content/categories/themes.md
Labels: Documentation

#686 Update start.md
  documentation/content/configuration/start.md
Labels: Documentation

#687 adding explanations to lovelace plugins
  documentation/content/categories/plugins.md
Labels: Documentation

#688 adding explanations to integrations
  documentation/content/categories/integrations.md
Labels: Documentation

#690 Update options.md
  documentation/content/configuration/options.md
Labels: Documentation

#691 Added custom component for Atag One Thermostat
  repositories/integration
Labels: New default repository

#692 Add panasonic cloud comfort integration
  repositories/integration
Labels: New default repository

#696 Update options.md
  documentation/content/configuration/options.md
Labels: Documentation

#698 Add media_player.linkplay integration
  repositories/integration
Labels: New default repository

#466 Add robmarkcole components
  repositories/integration
Labels: New default repository

#711 Add plugin azuwis/zigbee2mqtt-networkmap
  repositories/plugin
Labels: New default repository

#713 Explain why HACS needs a Github Token
  documentation/content/configuration/pat.md
Labels: Documentation

#726 Fix dead link in integration front-end
  custom_components/hacs/strings.json
Labels: Hacktoberfest

#741 fix blacklist message
  custom_components/hacs/hacsbase/__init__.py
Labels: Backend, Hacktoberfest

#743 Update workflow for backend testing
  .devcontainer/sample_configuration.yaml
  .github/workflows/BackendTest.yml
  custom_components/hacs/manifest.json
Labels: Hacktoberfest

#750 Update base.html
  custom_components/hacs/frontend/templates/base.html
Labels: Hacktoberfest
