Repository hacs/integration, pull requests merged in 2019-08, with the labels that each got.

#361 Add `var` integration to HACS
  repositories/integration
Labels: New default repository

#363 Move BKK Stop Information custom Lovelace card in its own repository
  repositories/plugin
Labels: New default repository

#367 add notifreeze repo/app
  repositories/appdaemon
Labels: New default repository

#366 Add discord_game custom integration
  repositories/integration
Labels: New default repository

#368 Convert BKK Stop Card naming to standard one
  repositories/plugin
Labels: New default repository

#369 Blacklist underscored BKK Stop Card
  repositories/blacklist
Labels: New default repository

#370 Add templatebinarysensor integration
  repositories/integration
Labels: New default repository

#371 Update discord_game repository
  repositories/blacklist
  repositories/integration
Labels: New default repository

#372 Add search-card plugin
  repositories/plugin
Labels: New default repository

#374 Add spotcast
  repositories/integration
Labels: New default repository

#380 add AutoMoLi & BatteryCheck app
  repositories/appdaemon
Labels: New default repository

#386 Add lovelace-gen
  repositories/integration
Labels: New default repository

#392 Xiaomi IR Remote Climate Integration
  repositories/integration
Labels: New default repository

#395 Add garbage collection sensor Acv-groep
  repositories/integration
Labels: New default repository

#397 Add Omnik Solar Inverter integration
  repositories/integration
Labels: New default repository

#398 Add rejseplanen-card plugin
  repositories/plugin
Labels: New default repository

#418 Docs: add example for advanced template usage
  docs/developer/general.md
  docs/images/info_jinja_here.png
Labels: Documentation

#419 Added HTML card by PiotrMachowski
  repositories/plugin
Labels: New default repository

#428 Add Husqvarna Automower integration
  repositories/integration
Labels: New default repository

#429 Add thomasloven/hass-favicon
  repositories/integration
Labels: New default repository

#430 Add Custom ISY994 Component
  repositories/integration
Labels: New default repository

#431 Updated compatible Home Assistant version
  docs/installation/manual.md
Labels: Documentation

#438 add eifinger/open_route_service
  repositories/integration
Labels: New default repository

#441 add synthwave theme repos
  repositories/plugin
  repositories/theme
Labels: Manual review required, New default repository

#444 added lovelace-animated-background
  repositories/plugin
Labels: New default repository

#442 add appdaemon-deconz-xiaomi-button
  repositories/appdaemon
Labels: New default repository

#448 fix file ending for manifest.json in repo setup instructions
  docs/developer/integration.md
Labels: Documentation

#447 Add lovelace-media-art-background
  repositories/plugin
Labels: New default repository

#453 Add enriqg9/dual-thermostat
  repositories/plugin
Labels: New default repository

#461 add openmensa integration
  repositories/integration
Labels: Manual review required, New default repository

#462 Add NHL API Integration
  repositories/integration
Labels: New default repository

#459 Add lovelace-valetudo-map-card
  repositories/plugin
Labels: New default repository

#469 Add Climate_IP device integration
  repositories/integration
Labels: New default repository

#475 add openmensa-lovelace-card
  repositories/plugin
Labels: New default repository

#479 Add plugin power-wheel-card
  repositories/plugin
Labels: New default repository

#481 Add Beward devices integration
  repositories/integration
Labels: New default repository

#482 Add Average sensor
  repositories/integration
Labels: New default repository

#480 Add garbage_collection sensor
  repositories/integration
Labels: New default repository

#486 Add clean up snapshots repo
  repositories/integration
Labels: New default repository

#492 Add CZ-Public-Transport integration
  repositories/integration
Labels: New default repository

#495 Add Mementary Switch Component
  repositories/integration
Labels: New default repository

#496 Update alexa_media_player to new project location
  repositories/blacklist
  repositories/integration
Labels: New default repository
