Repository hacs/integration, pull requests merged in 2019-09, with the labels that each got.

#498 Add digitalSTROM component
  repositories/integration
Labels: New default repository

#504 Add Gismeteo Weather Provider component
  repositories/integration
Labels: New default repository

#506 Add Garbage Collection custom card
  repositories/plugin
Labels: New default repository

#507 Add growatt integration
  repositories/integration
Labels: New default repository

#509 Add Laser Egg sensor
  repositories/integration
Labels: New default repository

#511 Fixed missing entry
  repositories/integration
Labels: New default repository

#516 Addition of GoogleGeocode-HASS
  repositories/integration
Labels: New default repository

#517 Addition of Anniversaries
  repositories/integration
Labels: New default repository

#523 Fix issues with blank files after save
  custom_components/hacs/__init__.py
  custom_components/hacs/hacsbase/backup.py
  custom_components/hacs/hacsbase/data.py
  custom_components/hacs/http.py
Labels: Backend

#525 Change MD render logic
  custom_components/hacs/manifest.json
  custom_components/hacs/repositories/repository.py
Labels: Backend

#527 Enable country filtering
  custom_components/hacs/.translations/en.json
  custom_components/hacs/__init__.py
  custom_components/hacs/config_flow.py
  custom_components/hacs/frontend/templates/overviews.html
  custom_components/hacs/hacsbase/configuration.py
  custom_components/hacs/hacsbase/data.py
  custom_components/hacs/repositories/manifest.py
  docs/installation/configuration.md
Labels: Backend, Documentation, Frontend

#529 Add Area Reiniging integration to HACS
  repositories/integration
Labels: New default repository

#532 Add FRITZ!Box Tools integration
  repositories/integration
Labels: New default repository

#534 Add DPC sensor (Civil Protection Department Italy)
  repositories/integration
Labels: New default repository

#543 Add flex-horseshoe-card
  repositories/plugin
Labels: New default repository

#544 Update upgrade_all.html
  custom_components/hacs/frontend/templates/modal/upgrade_all.html
Labels: Frontend

#548 Remove device_info property
  custom_components/hacs/sensor.py
Labels: Backend

#549 Fix incorrect configuration link
  docs/installation/manual.md
Labels: Documentation

#550 Merge beta into master for 0.14 release
  .devcontainer/Dockerfile
  .devcontainer/custom_component_helper
  .devcontainer/devcontainer.json
  .devcontainer/tabnine_config.json
  .github/workflows/lint_data_branch.yml
  .github/workflows/test_with_home_assistant.yml
  .vscode/tasks.json
  README.md
  custom_components/hacs/.translations/en.json
  custom_components/hacs/.translations/pl.json
  custom_components/hacs/.translations/ru.json
  custom_components/hacs/__init__.py
  custom_components/hacs/config_flow.py
  custom_components/hacs/const.py
  custom_components/hacs/frontend/elements/hacs.js
  custom_components/hacs/frontend/templates/grid.html
  custom_components/hacs/frontend/templates/repository/authors.html
  custom_components/hacs/frontend/templates/table.html
  custom_components/hacs/hacs.json
  custom_components/hacs/hacsbase/__init__.py
  custom_components/hacs/hacsbase/backup.py
  custom_components/hacs/hacsbase/configuration.py
  custom_components/hacs/hacsbase/const.py
  custom_components/hacs/hacsbase/data.py
  custom_components/hacs/hacsbase/migration.py
  custom_components/hacs/manifest.json
  custom_components/hacs/repositories/appdaemon.py
  custom_components/hacs/repositories/integration.py
  custom_components/hacs/repositories/manifest.py
  custom_components/hacs/repositories/plugin.py
  custom_components/hacs/repositories/python_script.py
  custom_components/hacs/repositories/repository.py
  custom_components/hacs/repositories/theme.py
  custom_components/hacs/sensor.py
  docs/images/select_issue_template.png
  docs/index.md
  docs/installation/configuration.md
  docs/installation/manual.md
  docs/issues.md
  mkdocs.yml
  requirements.txt
Labels: Backend, Documentation, Frontend

#558 Add french translation
  custom_components/hacs/.translations/fr.json
Labels: Translation

#494 Added HTML Jinja2 Template card
  repositories/plugin
Labels: New default repository

#559 Add Car Wash binary sensor
  repositories/integration
Labels: New default repository

#561 Added SIA integration.
  repositories/integration
Labels: New default repository

#564 Spanish Translation
  custom_components/hacs/.translations/es.json
Labels: Translation

#562 added climate group
  repositories/integration
Labels: New default repository

#568 Add Xiaomi mi Flora and Flower Care™ Smart Monitor integration component
  repositories/integration
Labels: New default repository

#571 Add repository for Zwift Component
  repositories/integration
Labels: New default repository

#572 replace batterycheck with entitycheck
  repositories/appdaemon
  repositories/blacklist
Labels: New default repository
