Repository hacs/integration, pull requests merged in 2021-01, with the labels that each got.

#1744 Simplify serving files and cache
  custom_components/hacs/helpers/functions/file_etag.py
  custom_components/hacs/manifest.json
  custom_components/hacs/webresponses/category.py
  requirements.txt
  tests/helpers/functions/test_etag.py
Labels: pr: bugfix

#1778 Remove support/testing for Python 3.7
  .github/pre-commit-config.yaml
  .github/workflows/homeassistant.yml
  .github/workflows/pytest.yml
  Makefile
  requirements.txt
Labels: Breaking Change

#1777 Fix issue with VERSION const
  .github/workflows/release.yml
  custom_components/hacs/const.py
  custom_components/hacs/hacsbase/data.py
  custom_components/hacs/models/system.py
  custom_components/hacs/operational/setup.py
  custom_components/hacs/operational/setup_actions/load_hacs_repository.py
  custom_components/hacs/sensor.py
Labels: pr: bugfix

#1780 Except ValueError in functions/information
  custom_components/hacs/helpers/functions/information.py
Labels: pr: bugfix

#1781 Fix max vs min typo @KTibow
  custom_components/hacs/manifest.json
  requirements.txt
Labels: pr: bugfix, pr: dependency-update

#1782 Change devcontainer from `ludeeus/container` to `ghcr.io/ludeeus/devcontainer/integration`
  .devcontainer/devcontainer.json
  .github/release-drafter.yml
  Makefile
  custom_components/hacs/helpers/functions/constrains.py
  custom_components/hacs/operational/setup.py
Labels: pr: enhancement

#1785 Add underline to custom repository URL @ludeeus
  custom_components/hacs/manifest.json
  requirements.txt
Labels: pr: enhancement

#1786 Force Content-Type for frontend
  custom_components/hacs/operational/setup.py
  custom_components/hacs/operational/setup_actions/frontend.py
  custom_components/hacs/webresponses/frontend.py
Labels: pr: enhancement

#1787 Fix reconnect yaml mode during startup
  custom_components/hacs/operational/setup.py
Labels: pr: bugfix

#1788 Use progress step for config_flow
  custom_components/hacs/__init__.py
  custom_components/hacs/base.py
  custom_components/hacs/config_flow.py
  custom_components/hacs/hacsbase/data.py
  custom_components/hacs/hacsbase/hacs.py
  custom_components/hacs/helpers/classes/repository.py
  custom_components/hacs/helpers/functions/misc.py
  custom_components/hacs/models/core.py
  custom_components/hacs/models/system.py
  custom_components/hacs/operational/backup.py
  custom_components/hacs/operational/factory.py
  custom_components/hacs/operational/setup.py
  custom_components/hacs/operational/setup_actions/categories.py
  custom_components/hacs/operational/setup_actions/clear_storage.py
  custom_components/hacs/operational/setup_actions/frontend.py
  custom_components/hacs/operational/setup_actions/load_hacs_repository.py
  custom_components/hacs/operational/setup_actions/sensor.py
  custom_components/hacs/operational/setup_actions/websocket_api.py
  custom_components/hacs/repositories/appdaemon.py
  custom_components/hacs/repositories/integration.py
  custom_components/hacs/repositories/netdaemon.py
  custom_components/hacs/repositories/python_script.py
  custom_components/hacs/repositories/theme.py
  custom_components/hacs/sensor.py
  custom_components/hacs/system_health.py
  custom_components/hacs/translations/en.json
  tests/async_mock.py
  tests/hacsbase/test_hacs.py
  tests/operational/setup_actions/test_categories_setup.py
  tests/repositories/test_integration_class.py
  tests/repositories/test_netdaemon_class.py
  tests/repositories/test_python_script.py
  tests/repositories/test_theme_class.py
  tests/validate/test_async_run_repository_checks.py
  tests/webresponses/test_frontend.py
Labels: pr: new-feature

#1839 Avoid some I/O in event loop
  custom_components/hacs/helpers/methods/installation.py
Labels: pr: enhancement

#1851 Add version key to manifest file
  .github/workflows/release.yml
  custom_components/hacs/manifest.json
  manage/update_manifest.py
  tests/helpers/misc/test_version_is_newer_than_version.py
Labels: pr: enhancement

#1853 Bump aiogithubapi to 21.1.1
  custom_components/hacs/manifest.json
  requirements.txt
Labels: dependencies

#1854 Bummp awesomeversion to 21.1.8
  custom_components/hacs/manifest.json
  requirements.txt
Labels: dependencies, pr: dependency-update

#1856 Remove HACS from hass.data on remove entry
  custom_components/hacs/operational/remove.py
Labels: pr: bugfix

#1857 Limit storage writes
  custom_components/hacs/helpers/functions/store.py
Labels: pr: enhancement

#1858 Abort option flow if HACS is not setup
  custom_components/hacs/config_flow.py
  custom_components/hacs/translations/en.json
Labels: pr: bugfix

#1860 Add async_remove_entry
  custom_components/hacs/__init__.py
Labels: pr: bugfix
