Repository hacs/integration, pull requests merged in 2021-11, with the labels that each got.

#2255 Update iconset to be usable with the icon picker
  custom_components/hacs/iconset.js
  custom_components/hacs/tasks/setup_frontend.py
Labels: pr: enhancement

#2260 Drop loop kwarg from async_timeout.timeout
  custom_components/hacs/helpers/functions/download.py
Labels: pr: bugfix

#2270 Remove aiofiles dependency
  custom_components/hacs/base.py
  custom_components/hacs/helpers/classes/repository.py
  custom_components/hacs/helpers/functions/download.py
  custom_components/hacs/helpers/functions/save.py
  custom_components/hacs/manifest.json
  requirements.txt
Labels: pr: refactor

#2273 Remove queueman dependency
  custom_components/hacs/base.py
  custom_components/hacs/exceptions.py
  custom_components/hacs/hacsbase/hacs.py
  custom_components/hacs/helpers/classes/repository.py
  custom_components/hacs/helpers/functions/download.py
  custom_components/hacs/manifest.json
  custom_components/hacs/operational/setup.py
  custom_components/hacs/share.py
  custom_components/hacs/tasks/setup_frontend.py
  custom_components/hacs/utils/decorator.py
  custom_components/hacs/utils/queue_manager.py
  requirements.txt
Labels: pr: refactor

#2274 Remove backoff dependency
  custom_components/hacs/helpers/functions/download.py
  custom_components/hacs/manifest.json
  requirements.txt
Labels: pr: refactor

#2275 Require 2021.9.0 as minimum Home Assistant version
  custom_components/hacs/iconset.js
  hacs.json
Labels: Breaking Change

#2276 Bump dessant/lock-threads from 2.1.2 to 3
  .github/workflows/lock.yml
Labels: pr: dependency-update

#2277 Upload zip on merge to main
  .github/workflows/publish.yml
Labels: pr: new-feature

#2281 Remove awesomeversion requirement
  custom_components/hacs/manifest.json
  requirements.txt
Labels: pr: refactor

#2282 Remove PyGithub dependency
  requirements.txt
Labels: pr: refactor

#2283 Fix issue with showingf correct version after restore
  custom_components/hacs/helpers/properties/pending_update.py
Labels: pr: bugfix

#2285 Handle repository renames of downloaded repositories
  custom_components/hacs/hacsbase/data.py
  custom_components/hacs/helpers/classes/repository.py
  custom_components/hacs/helpers/functions/download.py
  custom_components/hacs/helpers/functions/register_repository.py
Labels: pr: bugfix

#2301 Fix issues where the repo ID where 0
  custom_components/hacs/api/hacs_repository_data.py
  custom_components/hacs/hacsbase/data.py
Labels: pr: bugfix

#2302 Enable HACS before running startup tasks
  custom_components/hacs/base.py
  custom_components/hacs/operational/setup.py
Labels: pr: bugfix

#2304 Move websocket setup to task
  .codecov.yml
  custom_components/hacs/api/__init__.py
  custom_components/hacs/api/acknowledge_critical_repository.py
  custom_components/hacs/api/check_local_path.py
  custom_components/hacs/api/get_critical_repositories.py
  custom_components/hacs/api/hacs_config.py
  custom_components/hacs/api/hacs_removed.py
  custom_components/hacs/api/hacs_repositories.py
  custom_components/hacs/api/hacs_repository.py
  custom_components/hacs/api/hacs_repository_data.py
  custom_components/hacs/api/hacs_settings.py
  custom_components/hacs/api/hacs_status.py
  custom_components/hacs/tasks/setup_websocket_api.py
  tests/api/test_api.py
  tests/tasks/test_setup_websocket_api.py
Labels: pr: refactor

#2305 Simplify entity creation
  custom_components/hacs/sensor.py
  tests/test_sensor.py
Labels: pr: refactor

#2306 Add configuration_url
  custom_components/hacs/sensor.py
Labels: pr: new-feature

#2313 Simplify devcontainer files
  .devcontainer.json
  .devcontainer/sample_configuration.yaml
  .github/workflows/validate.yml
  .gitignore
  manage/integration_start
Labels: pr: refactor

#2314 Use required DeviceEntryType for HA 2021.12+
  custom_components/hacs/sensor.py
Labels: pr: bugfix
