Repository hacs/integration, pull requests merged in 2021-06, with the labels that each got.

#1995 Reduce number of disk reads and writes to storage
  custom_components/hacs/hacsbase/data.py
  custom_components/hacs/hacsbase/hacs.py
  custom_components/hacs/helpers/classes/repository.py
  custom_components/hacs/helpers/classes/repositorydata.py
  custom_components/hacs/helpers/functions/register_repository.py
  custom_components/hacs/helpers/functions/store.py
  tests/hacsbase/test_hacs.py
  tests/hacsbase/test_hacsbase_data.py
  tests/helpers/classes/test_repository_data.py
  tests/test_sensor.py
Labels: Breaking Change, pr: enhancement

#2075 Ignore lovelace KeyError
  custom_components/hacs/operational/setup.py
Labels: pr: bugfix

#2076 Set minimum HA version to 2021.2.0
  custom_components/hacs/const.py
  hacs.json
Labels: Breaking Change

#2079 Block <= 0 && >100 for release count
  .devcontainer/sample_configuration.yaml
  custom_components/hacs/config_flow.py
  custom_components/hacs/translations/en.json
Labels: pr: bugfix

#2085 Use cache if storage mode
  custom_components/hacs/base.py
  custom_components/hacs/hacsbase/hacs.py
  custom_components/hacs/models/core.py
  custom_components/hacs/operational/setup.py
  custom_components/hacs/operational/setup_actions/frontend.py
  tests/test_globals.py
Labels: pr: enhancement

#2087 Pass in validate when updating with zip and wrap dowload_repository_content in try/except
  custom_components/hacs/helpers/functions/download.py
  custom_components/hacs/helpers/methods/installation.py
Labels: pr: bugfix

#2096 Update frontend to 20210620130608
  custom_components/hacs/manifest.json
  requirements.txt
Labels: dependencies

#2100 Update frontend to 20210620205902
  custom_components/hacs/manifest.json
  requirements.txt
Labels: pr: dependency-update
