Repository hacs/integration, pull requests merged in 2022-01, with the labels that each got.

#2429 Restore local path
  custom_components/hacs/repositories/integration.py
  custom_components/hacs/utils/data.py
  tests/stories/test_registration.py
Labels: pr: bugfix

#2434 Don't exit early if force for update_repository
  custom_components/hacs/repositories/appdaemon.py
  custom_components/hacs/repositories/integration.py
  custom_components/hacs/repositories/netdaemon.py
  custom_components/hacs/repositories/plugin.py
  custom_components/hacs/repositories/python_script.py
  custom_components/hacs/repositories/theme.py
Labels: pr: bugfix

#2438 Force data update for all WS commands
  custom_components/hacs/tasks/setup_websocket_api.py
Labels: pr: bugfix

#2444 Use https for install instead of git
  .github/workflows/pytest.yml
  Makefile
Labels: pr: bugfix

#2442 Limit concurrent delay to only when needed
  custom_components/hacs/utils/decorator.py
Labels: pr: bugfix

#2443 Force data update on installation
  custom_components/hacs/repositories/base.py
  custom_components/hacs/utils/decorator.py
  tests/common.py
Labels: pr: bugfix

#2446 Catch HacsException in common_update
  custom_components/hacs/repositories/base.py
Labels: pr: bugfix

#2459 Fix test fixtures
  tests/common.py
  tests/tasks/test_setup_frontend.py
Labels: pr: bugfix

#2460 Add diagnostics support
  custom_components/hacs/diagnostics.py
  tests/test_confiig_flow.py
  tests/test_diagnostics.py
Labels: pr: new-feature

#2461 Retry setup every 5 min if not disabled
  custom_components/hacs/base.py
Labels: pr: bugfix

#2462 Allow rate limit check to run when not running
  custom_components/hacs/tasks/check_ratelimit.py
  tests/tasks/test_check_ratelimit.py
Labels: pr: bugfix

#2464 Use compare result in pending_update
  custom_components/hacs/repositories/base.py
  custom_components/hacs/utils/version.py
  tests/utils/test_version.py
Labels: pr: bugfix

#2468 Add DOMAIN_OVERRIDES workaround
  custom_components/hacs/repositories/base.py
  custom_components/hacs/utils/workarounds.py
  tests/utils/test_workarounds.py
Labels: pr: bugfix

#2466 Add more data to diagnostics platform
  custom_components/hacs/diagnostics.py
  custom_components/hacs/repositories/base.py
  tests/conftest.py
  tests/test_diagnostics.py
Labels: pr: enhancement

#2478 Handle missing repository_object during removal
  custom_components/hacs/repositories/base.py
Labels: pr: bugfix

#2479 Add base repositories data file
  .github/pre-commit-config.yaml
  Makefile
  custom_components/hacs/base.py
  custom_components/hacs/utils/data.py
  custom_components/hacs/utils/default.repositories
  manage/update_default_repositories.py
  tests/hacsbase/test_hacsbase_data.py
Labels: pr: enhancement

#2482 Remove unused import
  custom_components/hacs/tasks/check_ratelimit.py
Labels: pr: refactor
