Repository hacs/integration, pull requests merged in 2022-05, with the labels that each got.

#2664 Fixed a typo in debug logging for queue_manager
  custom_components/hacs/utils/queue_manager.py
Labels: pr: refactor

#2672 Set Home Assistant 2022.4.0 as minimum version
  custom_components/hacs/__init__.py
  custom_components/hacs/base.py
  custom_components/hacs/manifest.json
  custom_components/hacs/repositories/base.py
  custom_components/hacs/sensor.py
  hacs.json
Labels: Breaking Change

#2673 Bump frontend to 20220514073057
  Makefile
  manage/install_frontend
Labels: dependencies

#2683 Add filtering to releasenotes
  custom_components/hacs/websocket.py
Labels: pr: enhancement

#2685 Bump frontend to 20220522154357
  manage/install_frontend
Labels: dependencies

#2686 Bump frontend to 20220522162559
  manage/install_frontend
Labels: dependencies

#2706 Restore last_version
  custom_components/hacs/utils/data.py
Labels: pr: bugfix

#2709 Allow integrations to not have codeowner/name in the manifest
  custom_components/hacs/repositories/integration.py
Labels: pr: enhancement

#2716 Ignore issues for downloaded repositories
  custom_components/hacs/base.py
Labels: pr: bugfix

#2713 Bump frontend to 20220528172839
  manage/install_frontend
Labels: dependencies

#2719 Bump frontend to 20220529113750
  manage/install_frontend
Labels: dependencies

#2720 Bump frontend to 20220529163432
  manage/install_frontend
Labels: dependencies

#2723 Bump frontend to 20220529181005
  manage/install_frontend
Labels: dependencies
