Repository hacs/integration, pull requests merged in 2022-04, with the labels that each got.

#2585 Remove title from user step
  custom_components/hacs/translations/en.json
Labels: pr: bugfix

#2586 Use _attr_native_unit_of_measurement
  custom_components/hacs/sensor.py
Labels: pr: bugfix

#2584 Use installed_version for the update entity
  .github/pre-commit-config.yaml
  custom_components/hacs/update.py
Labels: Experimental

#2587 Add back current_version for compatibility
  custom_components/hacs/update.py
Labels: Experimental

#2592 Fix version constraint for remove and recreate entity devices
  custom_components/hacs/base.py
  custom_components/hacs/repositories/base.py
Labels: Experimental

#2593 Add event filter to limit entity updates
  custom_components/hacs/entity.py
  custom_components/hacs/repositories/appdaemon.py
  custom_components/hacs/repositories/base.py
  custom_components/hacs/repositories/integration.py
  custom_components/hacs/repositories/netdaemon.py
  custom_components/hacs/repositories/plugin.py
  custom_components/hacs/repositories/python_script.py
  custom_components/hacs/repositories/theme.py
Labels: pr: enhancement

#2591 Adjust link to FAQ
  README.md
  info.md
Labels: pr: refactor

#2594 Implement entity_picture for update entities
  custom_components/hacs/update.py
Labels: Experimental

#2604 Remove beta workarouds
  custom_components/hacs/update.py
Labels: Experimental

#2603 Do not mark restart required when download fails
  custom_components/hacs/repositories/base.py
Labels: pr: bugfix

#2605 Return result in decorator
  custom_components/hacs/utils/decorator.py
Labels: pr: bugfix

#2608 Hide install if update can't be downloaded
  custom_components/hacs/update.py
Labels: Experimental

#2609 Adjust loggers
  custom_components/hacs/base.py
  custom_components/hacs/entity.py
  custom_components/hacs/repositories/appdaemon.py
  custom_components/hacs/repositories/base.py
  custom_components/hacs/repositories/integration.py
  custom_components/hacs/repositories/netdaemon.py
  custom_components/hacs/repositories/plugin.py
  custom_components/hacs/repositories/python_script.py
  custom_components/hacs/repositories/theme.py
  custom_components/hacs/tasks/base.py
  custom_components/hacs/tasks/manager.py
  custom_components/hacs/tasks/update_all_repositories.py
  custom_components/hacs/tasks/update_downloaded_repositories.py
  custom_components/hacs/utils/data.py
  custom_components/hacs/utils/queue_manager.py
  custom_components/hacs/utils/store.py
  custom_components/hacs/validate/manager.py
  tests/tasks/test_check_ratelimit.py
  tests/tasks/test_prosess_queue.py
  tests/utils/test_store.py
Labels: pr: refactor

#2616 Mask network issues
  custom_components/hacs/base.py
Labels: pr: refactor

#2617 Set Home Assistant 2022.3.0 as minimum version
  .github/workflows/pytest.yml
  .github/workflows/validate.yml
  Makefile
  custom_components/hacs/entity.py
  custom_components/hacs/iconset.js
  custom_components/hacs/manifest.json
  hacs.json
  tests/tasks/test_setup_update_platform.py
  tests/test_sensor.py
Labels: Breaking Change

#2619 Use atomic_writes when storing data
  custom_components/hacs/utils/data.py
  custom_components/hacs/utils/store.py
Labels: pr: enhancement

#2620 Use async_at_start helper for startup task
  custom_components/hacs/__init__.py
  custom_components/hacs/base.py
Labels: pr: refactor

#2621 Remove all hacs/* events in favour of dispatcher and WS subscriptions
  custom_components/hacs/__init__.py
  custom_components/hacs/base.py
  custom_components/hacs/entity.py
  custom_components/hacs/enums.py
  custom_components/hacs/repositories/appdaemon.py
  custom_components/hacs/repositories/base.py
  custom_components/hacs/repositories/integration.py
  custom_components/hacs/repositories/netdaemon.py
  custom_components/hacs/repositories/plugin.py
  custom_components/hacs/repositories/python_script.py
  custom_components/hacs/repositories/theme.py
  custom_components/hacs/tasks/setup_websocket_api.py
  custom_components/hacs/tasks/update_all_repositories.py
  custom_components/hacs/utils/data.py
  custom_components/hacs/utils/decorator.py
  manage/install_frontend
  tests/conftest.py
  tests/tasks/test_setup_websocket_api.py
  tests/test_sensor.py
Labels: Breaking Change

#2622 Remove update coordinator
  custom_components/hacs/__init__.py
  custom_components/hacs/base.py
  custom_components/hacs/entity.py
  tests/conftest.py
Labels: pr: refactor

#2623 Refactor setup tasks
  .github/workflows/validate.yml
  custom_components/hacs/__init__.py
  custom_components/hacs/base.py
  custom_components/hacs/frontend.py
  custom_components/hacs/tasks/activate_categories.py
  custom_components/hacs/tasks/check_constrains.py
  custom_components/hacs/tasks/check_ratelimit.py
  custom_components/hacs/tasks/clear_old_storage.py
  custom_components/hacs/tasks/restore_data.py
  custom_components/hacs/tasks/setup_frontend.py
  custom_components/hacs/tasks/setup_sensor_platform.py
  custom_components/hacs/tasks/setup_update_platform.py
  custom_components/hacs/tasks/verify_api.py
  custom_components/hacs/websocket.py
  tests/api/test_api.py
  tests/tasks/test_activate_categories.py
  tests/tasks/test_check_constrains.py
  tests/tasks/test_clear_old_storage.py
  tests/tasks/test_restore_data.py
  tests/tasks/test_setup_frontend.py
  tests/tasks/test_setup_sensor_platform.py
  tests/tasks/test_setup_update_platform.py
  tests/tasks/test_setup_websocket_api.py
  tests/tasks/test_verify_api.py
Labels: pr: refactor

#2624 Refactor remaining tasks
  .codecov.yml
  custom_components/hacs/__init__.py
  custom_components/hacs/base.py
  custom_components/hacs/tasks/__init__.py
  custom_components/hacs/tasks/base.py
  custom_components/hacs/tasks/check_ratelimit.py
  custom_components/hacs/tasks/handle_critical_notification.py
  custom_components/hacs/tasks/load_hacs_repository.py
  custom_components/hacs/tasks/manager.py
  custom_components/hacs/tasks/prosess_queue.py
  custom_components/hacs/tasks/store_hacs_data.py
  custom_components/hacs/tasks/update_all_repositories.py
  custom_components/hacs/tasks/update_critical_repositories.py
  custom_components/hacs/tasks/update_default_repositories.py
  custom_components/hacs/tasks/update_downloaded_repositories.py
  custom_components/hacs/tasks/update_removed_repositories.py
  custom_components/hacs/utils/data.py
  custom_components/hacs/utils/queue_manager.py
  tests/conftest.py
  tests/hacsbase/test_hacs.py
  tests/tasks/__init__.py
  tests/tasks/test_check_ratelimit.py
  tests/tasks/test_handle_critical_notification.py
  tests/tasks/test_load_hacs_repository.py
  tests/tasks/test_prosess_queue.py
  tests/tasks/test_store_hacs_data.py
  tests/tasks/test_update_all_repositories.py
  tests/tasks/test_update_critical_repositories.py
  tests/tasks/test_update_downloaded_repositories.py
  tests/tasks/test_update_removed_repositories.py
Labels: pr: refactor

#2625 Add progress attribute to update entity
  custom_components/hacs/enums.py
  custom_components/hacs/repositories/base.py
  custom_components/hacs/update.py
Labels: Experimental

#2626 Enable experimental downloader for all categories
  custom_components/hacs/base.py
  custom_components/hacs/repositories/base.py
Labels: Experimental

#2627 Do not load validators outside of action
  custom_components/hacs/__init__.py
  custom_components/hacs/repositories/base.py
  custom_components/hacs/validate/README.md
  custom_components/hacs/validate/base.py
  custom_components/hacs/validate/hacs_manifest.py
  custom_components/hacs/validate/integration_manifest.py
  custom_components/hacs/validate/manager.py
  custom_components/hacs/validate/repository_description.py
  custom_components/hacs/validate/repository_information_file.py
  custom_components/hacs/validate/repository_topics.py
  tests/validate/test_async_run_repository_checks.py
  tests/validate/test_base_valiadte_classes.py
Labels: pr: refactor

#2628 Do not add sensor attributes if update entities are enabled
  custom_components/hacs/sensor.py
  tests/validate/test_async_run_repository_checks.py
Labels: Experimental

#2629 Repositiry data cleanup
  custom_components/hacs/base.py
  custom_components/hacs/repositories/appdaemon.py
  custom_components/hacs/repositories/base.py
  custom_components/hacs/repositories/integration.py
  custom_components/hacs/repositories/netdaemon.py
  custom_components/hacs/repositories/plugin.py
  custom_components/hacs/repositories/python_script.py
  custom_components/hacs/repositories/theme.py
  custom_components/hacs/update.py
  custom_components/hacs/utils/data.py
  custom_components/hacs/utils/store.py
  custom_components/hacs/websocket.py
  tests/hacsbase/test_configuration.py
  tests/hacsbase/test_hacsbase_data.py
  tests/helpers/classes/test_repository_data.py
  tests/helpers/download/test_gather_files_to_download.py
  tests/helpers/download/test_should_try_releases.py
  tests/helpers/information/test_find_file_name.py
  tests/repositories/helpers/test_properties.py
  tests/repositories/test_can_install.py
  tests/repositories/test_core.py
  tests/repositories/test_data.py
  tests/repositories/test_hacs_manifest.py
  tests/utils/test_store.py
  tests/validate/common/test_repository_information_file_check.py
Labels: pr: refactor

#2630 Limit writes
  custom_components/hacs/base.py
  custom_components/hacs/utils/data.py
  tests/repositories/test_can_install.py
Labels: pr: refactor

#2633 Move version_to_download to Repository base class
  custom_components/hacs/repositories/base.py
  custom_components/hacs/repositories/integration.py
  custom_components/hacs/utils/version.py
  tests/common.py
  tests/utils/test_version.py
Labels: pr: refactor

#2634 Add reauthentication flow
  custom_components/hacs/__init__.py
  custom_components/hacs/base.py
  custom_components/hacs/config_flow.py
  custom_components/hacs/translations/en.json
Labels: pr: new-feature
