Repository hacs/integration, pull requests merged in 2022-02, with the labels that each got.

#2488 Move scheduled tasks out of HacsBase and to dedicated tasks
  custom_components/hacs/__init__.py
  custom_components/hacs/base.py
  custom_components/hacs/tasks/handle_critical_notification.py
  custom_components/hacs/tasks/update_all_repositories.py
  custom_components/hacs/tasks/update_critical_repositories.py
  custom_components/hacs/tasks/update_default_repositories.py
  custom_components/hacs/tasks/update_downloaded_repositories.py
  custom_components/hacs/tasks/update_removed_repositories.py
  manage/update_default_repositories.py
  tests/tasks/test_handle_critical_notification.py
  tests/tasks/test_update_all_repositories.py
  tests/tasks/test_update_critical_repositories.py
  tests/tasks/test_update_downloaded_repositories.py
  tests/tasks/test_update_removed_repositories.py
Labels: pr: refactor

#2489 Clear stage on unload
  custom_components/hacs/__init__.py
Labels: pr: refactor

#2490 Use 2h for remove update interval
  custom_components/hacs/tasks/update_critical_repositories.py
  custom_components/hacs/tasks/update_removed_repositories.py
Labels: pr: refactor

#2491 Remove background_task status
  custom_components/hacs/base.py
  custom_components/hacs/diagnostics.py
  custom_components/hacs/sensor.py
  custom_components/hacs/tasks/manager.py
  custom_components/hacs/tasks/prosess_queue.py
  custom_components/hacs/tasks/setup_websocket_api.py
  custom_components/hacs/tasks/update_all_repositories.py
  custom_components/hacs/tasks/update_downloaded_repositories.py
  custom_components/hacs/utils/data.py
  tests/conftest.py
  tests/hacsbase/test_hacsbase_data.py
  tests/test_sensor.py
Labels: pr: refactor

#2492 Don't send category updates to queue
  custom_components/hacs/sensor.py
  custom_components/hacs/tasks/update_default_repositories.py
  custom_components/hacs/utils/default.repositories
  tests/test_sensor.py
Labels: pr: refactor

#2501 Store information about releases
  custom_components/hacs/tasks/load_hacs_repository.py
  custom_components/hacs/tasks/update_downloaded_repositories.py
  custom_components/hacs/utils/data.py
  custom_components/hacs/utils/default.repositories
  tests/conftest.py
  tests/tasks/test_update_downloaded_repositories.py
Labels: pr: bugfix

#2504 Identify community add-on repositories
  custom_components/hacs/repositories/integration.py
Labels: pr: enhancement

#2507 Cleanup add-on detection exceptions
  custom_components/hacs/base.py
  custom_components/hacs/exceptions.py
  custom_components/hacs/repositories/integration.py
  tests/stories/test_registration.py
Labels: pr: refactor

#2508 Move get_releases to new API
  custom_components/hacs/repositories/base.py
  custom_components/hacs/tasks/setup_websocket_api.py
  tests/conftest.py
Labels: pr: refactor

#2519 Allow ignoring repositories
  custom_components/hacs/base.py
  custom_components/hacs/diagnostics.py
  custom_components/hacs/repositories/base.py
  custom_components/hacs/tasks/setup_websocket_api.py
  custom_components/hacs/tasks/update_default_repositories.py
  custom_components/hacs/tasks/update_removed_repositories.py
  custom_components/hacs/utils/data.py
  tests/conftest.py
  tests/helpers/information/test_find_file_name.py
  tests/tasks/test_setup_websocket_api.py
Labels: pr: new-feature

#2520 Fix download URL for release assets
  custom_components/hacs/repositories/base.py
Labels: pr: bugfix

#2523 Update Configuration link
  README.md
  info.md
Labels: pr: refactor
