Repository hacs/integration, pull requests merged in 2023-01, with the labels that each got.

#2978 Limit API usage for scheduled refresh
  custom_components/hacs/base.py
Labels: pr: refactor

#2979 Bump experimental frontend to 20230105194043
  manage/install_frontend
Labels: pr: dependency-update

#2990 Add base client to get data from R2
  custom_components/hacs/__init__.py
  custom_components/hacs/base.py
  custom_components/hacs/data_client.py
  scripts/data/generate_category_data.py
Labels: pr: new-feature

#2993 Remove unused pushed_at attribute
  custom_components/hacs/repositories/base.py
  custom_components/hacs/utils/data.py
  scripts/data/generate_category_data.py
  tests/fixtures/repository_data.json
  tests/repositories/test_data.py
  tests/sample_data.py
Labels: pr: refactor

#2991 Use data stored in Cloudflare R2 instead of GitHub API for scheduled refresh
  custom_components/hacs/base.py
  custom_components/hacs/repositories/base.py
  custom_components/hacs/system_health.py
  custom_components/hacs/utils/data.py
  scripts/data/generate_category_data.py
Labels: Experimental

#2996 Add client_name User Agent to DataClient
  custom_components/hacs/__init__.py
  custom_components/hacs/data_client.py
  scripts/data/generate_category_data.py
Labels: Experimental

#2997 Add etag support for data client
  custom_components/hacs/base.py
  custom_components/hacs/data_client.py
  scripts/data/generate_category_data.py
Labels: Experimental

#3000 Bump frontend to 20230114134102
  manage/install_frontend
Labels: Experimental

#3003 Require full_name for the repository before sending it to the frontend
  custom_components/hacs/websocket/repositories.py
Labels: pr: refactor

#3004 Drop refresh from API during startup
  custom_components/hacs/base.py
Labels: Experimental

#3006 Use different message for timeout error
  custom_components/hacs/data_client.py
Labels: Experimental

#3007 Limit stored data
  custom_components/hacs/const.py
  custom_components/hacs/utils/data.py
Labels: Experimental

#3008 Get critical repositories from R2
  custom_components/hacs/base.py
Labels: Experimental

#3009 Use last_fetched instead of full_name for checking what to send
  custom_components/hacs/websocket/repositories.py
Labels: Experimental

#3010 Add fallback fetch for hacs/integration
  custom_components/hacs/base.py
  custom_components/hacs/websocket/repositories.py
Labels: Experimental

#3012 Unregister stale custom repositories during startup
  custom_components/hacs/base.py
  custom_components/hacs/repositories/base.py
Labels: Experimental

#3013 Fix missing releases in update entities
  custom_components/hacs/update.py
Labels: Experimental

#3027 Always use 6 hours
  custom_components/hacs/base.py
Labels: pr: refactor

#3030 Adjust logging in WS and schedule
  custom_components/hacs/base.py
  custom_components/hacs/websocket/repositories.py
Labels: pr: refactor

#3031 Skip startup ratelimit check
  custom_components/hacs/__init__.py
Labels: Experimental

#3033 Update entities is always experimental
  custom_components/hacs/update.py
Labels: Experimental

#3034 Only show HACS data in system info for experimental
  custom_components/hacs/system_health.py
Labels: Experimental

#3038 Use async_forward_entry_setups instead of async_setup_platforms
  custom_components/hacs/__init__.py
Labels: pr: bugfix

#3041 Bump experimental frontend to 20230127100107
  manage/install_frontend
Labels: pr: dependency-update
