Repository hacs/integration, pull requests merged in 2024-05, with the labels that each got.

#3665 Add constraint for securesystemslib
  constraints.txt
Labels: pr: action

#3582 Adapt config flow to changes in HA Core 2024.2.0
  custom_components/hacs/config_flow.py
  tests/conftest.py
Labels: pr: bugfix

#3657 Add a cache to is_safe
  custom_components/hacs/utils/path.py
Labels: pr: refactor

#3572 Add coordinator for update entities
  custom_components/hacs/base.py
  custom_components/hacs/coordinator.py
  custom_components/hacs/entity.py
  custom_components/hacs/repositories/appdaemon.py
  custom_components/hacs/repositories/integration.py
  custom_components/hacs/repositories/netdaemon.py
  custom_components/hacs/repositories/plugin.py
  custom_components/hacs/repositories/python_script.py
  custom_components/hacs/repositories/template.py
  custom_components/hacs/repositories/theme.py
  custom_components/hacs/websocket/repository.py
  tests/snapshots/hacs-test-org/appdaemon-basic/test_update_entity_state.json
  tests/snapshots/hacs-test-org/integration-basic/test_update_entity_state.json
  tests/snapshots/hacs-test-org/plugin-basic/test_update_entity_state.json
  tests/snapshots/hacs-test-org/python_script-basic/test_update_entity_state.json
  tests/snapshots/hacs-test-org/template-basic/test_update_entity_state.json
  tests/snapshots/hacs-test-org/theme-basic/test_update_entity_state.json
Labels: pr: enhancement

#3609 Don't allow issues to be reported in tests
  tests/conftest.py
Labels: pr: test

#3647 Remove OrderedDict from api calls check
  tests/conftest.py
Labels: pr: test

#3676 Improve config flow test
  tests/test_config_flow.py
Labels: pr: test

#3679 Improve config flow test
  tests/test_config_flow.py
Labels: pr: test

#3685 Fix races in config flow tests
  tests/output/proxy_calls.json
  tests/test_config_flow.py
Labels: pr: test

#3673 Update async_test_home_assistant_dev
  tests/common.py
Labels: pr: test

#3694 Update async_test_home_assistant_dev (2024-05-21)
  tests/common.py
Labels: pr: test

#3675 Bump Python version used in CI
  .github/workflows/generate-hacs-data.yml
  .github/workflows/lint.yaml
  .github/workflows/publish.yml
  .github/workflows/validate.yml
Labels: pr: test

#3695 Add upload as part of the validation
  .github/workflows/validate.yml
Labels: pr: action

#3672 Bump minimum HA version to 2024.4.1
  .github/workflows/pytest.yml
  hacs.json
  requirements_core_min.txt
  requirements_test.txt
  tests/common.py
  tests/conftest.py
Labels: pr: dependency-update

#3697 Bump devcontainer to Python 3.12
  .devcontainer.json
Labels: pr: repository

#3698 Bump frontend to 20240522121116
  scripts/install/frontend
Labels: pr: dependency-update

#3584 Add async wrapper for commonly used filesystem functions
  custom_components/hacs/__init__.py
  custom_components/hacs/base.py
  custom_components/hacs/frontend.py
  custom_components/hacs/repositories/base.py
  custom_components/hacs/repositories/plugin.py
  custom_components/hacs/repositories/theme.py
  custom_components/hacs/utils/file_system.py
  tests/utils/test_fs_util.py
Labels: pr: enhancement

#3451 ✨ Display complete release notes
  custom_components/hacs/update.py
Labels: pr: enhancement

#3536 Avoid creating async_register_repository tasks to register_unknown_repositories
  custom_components/hacs/utils/data.py
Labels: pr: refactor

#3514 Adjust plugin filename scan for better performance
  custom_components/hacs/repositories/plugin.py
Labels: pr: refactor

#3702 Remove config entry mutation
  custom_components/hacs/base.py
Labels: pr: bugfix

#3701 Add python_script to after_dependencies
  custom_components/hacs/manifest.json
Labels: pr: bugfix

#3705 Fix typo in test name
  tests/utils/test_validate.py
Labels: pr: test

#3704 Remove some unused imports found by the bot
  custom_components/hacs/utils/path.py
  tests/conftest.py
  tests/test_config_flow.py
Labels: pr: refactor

#3565 Remove YAML configuration
  .github/workflows/validate.yml
  custom_components/hacs/__init__.py
  custom_components/hacs/diagnostics.py
  custom_components/hacs/translations/en.json
  custom_components/hacs/utils/configuration_schema.py
  tests/common.py
Labels: Breaking Change

#3585 Always enable experimental mode
  custom_components/hacs/base.py
  custom_components/hacs/config_flow.py
  custom_components/hacs/translations/en.json
  tests/hacsbase/test_configuration.py
  tests/snapshots/config_flow/test_full_user_flow_implementation.json
  tests/test_config_flow.py
Labels: Breaking Change

#3707 Remove some unused imports found by the bot
  custom_components/hacs/__init__.py
  custom_components/hacs/config_flow.py
Labels: pr: refactor

#3718 Fix some typos
  .github/workflows/validate.yml
  custom_components/hacs/validate/manager.py
  tests/validate/test_async_run_repository_checks.py
Labels: pr: refactor

#3706 Remove ConfigurationType enum
  custom_components/hacs/__init__.py
  custom_components/hacs/base.py
  custom_components/hacs/config_flow.py
  custom_components/hacs/enums.py
  custom_components/hacs/repositories/base.py
  custom_components/hacs/sensor.py
Labels: pr: refactor

#3719 Init ruff lint/format
  .devcontainer.json
  .github/pre-commit-config.yaml
  .github/workflows/lint.yaml
  action/action.py
  custom_components/hacs/__init__.py
  custom_components/hacs/base.py
  custom_components/hacs/config_flow.py
  custom_components/hacs/const.py
  custom_components/hacs/coordinator.py
  custom_components/hacs/data_client.py
  custom_components/hacs/diagnostics.py
  custom_components/hacs/entity.py
  custom_components/hacs/enums.py
  custom_components/hacs/frontend.py
  custom_components/hacs/repositories/__init__.py
  custom_components/hacs/repositories/appdaemon.py
  custom_components/hacs/repositories/base.py
  custom_components/hacs/repositories/integration.py
  custom_components/hacs/repositories/netdaemon.py
  custom_components/hacs/repositories/plugin.py
  custom_components/hacs/repositories/python_script.py
  custom_components/hacs/repositories/template.py
  custom_components/hacs/repositories/theme.py
  custom_components/hacs/sensor.py
  custom_components/hacs/system_health.py
  custom_components/hacs/utils/backup.py
  custom_components/hacs/utils/data.py
  custom_components/hacs/utils/decode.py
  custom_components/hacs/utils/decorator.py
  custom_components/hacs/utils/filters.py
  custom_components/hacs/utils/logger.py
  custom_components/hacs/utils/path.py
  custom_components/hacs/utils/queue_manager.py
  custom_components/hacs/utils/regex.py
  custom_components/hacs/utils/store.py
  custom_components/hacs/utils/template.py
  custom_components/hacs/utils/url.py
  custom_components/hacs/utils/validate.py
  custom_components/hacs/utils/version.py
  custom_components/hacs/utils/workarounds.py
  custom_components/hacs/validate/base.py
  custom_components/hacs/validate/manager.py
  custom_components/hacs/websocket/__init__.py
  custom_components/hacs/websocket/critical.py
  custom_components/hacs/websocket/repositories.py
  custom_components/hacs/websocket/repository.py
  pyproject.toml
  requirements_lint.txt
Labels: pr: refactor

#3720 Remove Pillow requirement
  requirements_test.txt
Labels: pr: refactor

#3721 Remove unused test requirements
  requirements_test.txt
Labels: pr: refactor

#3722 Remove template util
  custom_components/hacs/repositories/base.py
  custom_components/hacs/utils/template.py
  tests/handler/test_template.py
  tests/output/proxy_calls.json
Labels: Breaking Change, pr: refactor

#3726 Bump experimental frontend to 20240527114629
  scripts/install/frontend
Labels: pr: dependency-update

#3717 Remove sensor platform
  custom_components/hacs/__init__.py
  custom_components/hacs/base.py
  custom_components/hacs/sensor.py
Labels: pr: refactor

#3727 Only ship one frontend
  custom_components/hacs/frontend.py
  scripts/install/frontend
Labels: pr: refactor

#3732 Correct name of configuration test
  tests/hacsbase/test_configuration.py
Labels: pr: test

#3733 Bump frontend to 20240528140736
  scripts/install/frontend
Labels: pr: dependency-update

#3734 Fallback to the repo owner for manufacturer
  custom_components/hacs/entity.py
Labels: pr: enhancement

#3735 Fix some typos
  action/action.py
Labels: pr: refactor

#3739 Remove compatiblity with Python versions < 3.11
  custom_components/hacs/enums.py
Labels: pr: refactor

#3737 Add summary to generator
  .github/workflows/generate-hacs-data.yml
  .github/workflows/validate.yml
  scripts/data/generate_category_data.py
  tests/output/proxy_calls.json
Labels: pr: enhancement

#3740 Extend summary content
  scripts/data/generate_category_data.py
Labels: pr: enhancement

#3738 Remove compatibility with unsupported core versions
  action/action.py
  custom_components/hacs/utils/json.py
  scripts/data/generate_category_data.py
  tests/__init__.py
  tests/common.py
  tests/conftest.py
Labels: pr: refactor

#3742 Unload config entries after tests
  tests/conftest.py
  tests/output/proxy_calls.json
Labels: pr: test

#3743 Make the hass fixture async
  tests/conftest.py
Labels: pr: test
