Repository hacs/integration, pull requests merged in 2024-07, with the labels that each got.

#3844 Add workaround for old core versions to `HacsBase.async_recreate_entities`
  custom_components/hacs/base.py
Labels: pr: bugfix

#3841 Add pre-release information to exported data
  custom_components/hacs/repositories/base.py
  custom_components/hacs/utils/data.py
  custom_components/hacs/utils/validate.py
  scripts/data/generate_category_data.py
  tests/fixtures/proxy/api.github.com/repos/hacs-test-org/integration-basic/releases.json
  tests/fixtures/proxy/api.github.com/repos/hacs-test-org/integration-basic/releases/latest.json
  tests/output/proxy_calls.json
  tests/scripts/data/test_generate_category_data.py
  tests/snapshots/diagnostics/base.json
  tests/snapshots/diagnostics/exception.json
  tests/snapshots/scripts/data/generate_category_data_with_prior_content/integration/data.json
  tests/snapshots/scripts/data/generate_category_data_with_prior_content/integration/repositories.json
  tests/snapshots/scripts/data/generate_category_data_with_prior_content/integration/summary.json
Labels: pr: new-feature

#3846 Revert "Add pre-release information to exported data"
  custom_components/hacs/repositories/base.py
  custom_components/hacs/utils/data.py
  custom_components/hacs/utils/validate.py
  scripts/data/generate_category_data.py
  tests/fixtures/proxy/api.github.com/repos/hacs-test-org/integration-basic/releases.json
  tests/fixtures/proxy/api.github.com/repos/hacs-test-org/integration-basic/releases/latest.json
  tests/output/proxy_calls.json
  tests/scripts/data/test_generate_category_data.py
  tests/snapshots/diagnostics/base.json
  tests/snapshots/diagnostics/exception.json
  tests/snapshots/scripts/data/generate_category_data_with_prior_content/integration/data.json
  tests/snapshots/scripts/data/generate_category_data_with_prior_content/integration/repositories.json
  tests/snapshots/scripts/data/generate_category_data_with_prior_content/integration/summary.json
Labels: pr: bugfix

#3848 Use GraphQL to generate release content
  custom_components/hacs/repositories/base.py
  custom_components/hacs/utils/data.py
  custom_components/hacs/utils/validate.py
  scripts/data/generate_category_data.py
  tests/output/proxy_calls.json
  tests/scripts/data/test_generate_category_data.py
  tests/snapshots/diagnostics/base.json
  tests/snapshots/diagnostics/exception.json
  tests/snapshots/scripts/data/generate_category_data_with_prior_content/integration/data.json
  tests/snapshots/scripts/data/generate_category_data_with_prior_content/integration/repositories.json
  tests/snapshots/scripts/data/generate_category_data_with_prior_content/integration/summary.json
Labels: pr: refactor

#3840 Fix update entity missing after installing HACS
  custom_components/hacs/base.py
  tests/snapshots/hacs-test-org/appdaemon-basic/test_discard_invalid_repo_data.json
  tests/snapshots/hacs-test-org/appdaemon-basic/test_remove_repository_post.json
  tests/snapshots/hacs-test-org/appdaemon-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/appdaemon-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/integration-basic/test_discard_invalid_repo_data.json
  tests/snapshots/hacs-test-org/integration-basic/test_remove_repository_post.json
  tests/snapshots/hacs-test-org/integration-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/integration-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/plugin-basic/test_discard_invalid_repo_data.json
  tests/snapshots/hacs-test-org/plugin-basic/test_remove_repository_post.json
  tests/snapshots/hacs-test-org/plugin-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/plugin-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/python_script-basic/test_discard_invalid_repo_data.json
  tests/snapshots/hacs-test-org/python_script-basic/test_remove_repository_post.json
  tests/snapshots/hacs-test-org/python_script-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/python_script-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/template-basic/test_discard_invalid_repo_data.json
  tests/snapshots/hacs-test-org/template-basic/test_remove_repository_post.json
  tests/snapshots/hacs-test-org/template-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/template-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/theme-basic/test_discard_invalid_repo_data.json
  tests/snapshots/hacs-test-org/theme-basic/test_remove_repository_post.json
  tests/snapshots/hacs-test-org/theme-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/theme-basic/test_update_repository_websocket.json
  tests/snapshots/test_integration_setup.json
Labels: pr: bugfix

#3843 Remove local queue items after run
  custom_components/hacs/utils/queue_manager.py
Labels: pr: bugfix

#3853 Bump frontend to 20240704155809
  scripts/install/frontend
Labels: pr: dependency-update

#3857 Import json_loads from util instead of helpers
  custom_components/hacs/utils/json.py
Labels: pr: bugfix

#3856 Bump frontend to 20240705065257
  scripts/install/frontend
Labels: pr: dependency-update

#3588 Remove netdaemon support
  action/action.py
  custom_components/hacs/base.py
  custom_components/hacs/config_flow.py
  custom_components/hacs/diagnostics.py
  custom_components/hacs/enums.py
  custom_components/hacs/repositories/__init__.py
  custom_components/hacs/repositories/base.py
  custom_components/hacs/repositories/netdaemon.py
  custom_components/hacs/translations/en.json
  custom_components/hacs/utils/backup.py
  custom_components/hacs/utils/configuration_schema.py
  custom_components/hacs/utils/path.py
  custom_components/hacs/utils/validate.py
  tests/conftest.py
  tests/fixtures/v2-netdaemon-data.json
  tests/hacsbase/test_backup.py
  tests/hacsbase/test_configuration.py
  tests/helpers/download/test_gather_files_to_download.py
  tests/output/proxy_calls.json
  tests/snapshots/diagnostics/base.json
  tests/snapshots/diagnostics/exception.json
  tests/test_config_flow.py
  tests/utils/test_validate.py
Labels: Breaking Change

#3858 Minor lint update
  action/action.py
  custom_components/hacs/__init__.py
  custom_components/hacs/utils/backup.py
  pyproject.toml
  tests/action/test_hacs_action_integration.py
  tests/common.py
  tests/conftest.py
  tests/helpers/download/test_gather_files_to_download.py
  tests/helpers/filters/test_filter_content_return_one_of_type.py
  tests/helpers/filters/test_get_first_directory_in_directory.py
  tests/repositories/test_download_repository.py
  tests/repositories/test_get_documentation.py
  tests/repositories/test_plugin_repository.py
  tests/repositories/test_register_repository.py
  tests/repositories/test_remove_repository.py
  tests/repositories/test_removed_repository.py
  tests/repositories/test_update_repository.py
  tests/ruff.toml
  tests/scripts/data/test_generate_category_data.py
  tests/test_config_flow.py
  tests/test_data_client.py
  tests/test_diagnostics.py
  tests/test_update.py
  tests/utils/test_fs_util.py
  tests/utils/test_queue_manager.py
  tests/utils/test_store.py
  tests/utils/test_validate.py
  tests/validate/test_async_run_repository_checks.py
  tests/validate/test_brands_check.py
  tests/validate/test_integration_manifest_check.py
  tests/validate/test_repository_information_file_check.py
Labels: pr: refactor

#3859 Remove the release limit configuration
  custom_components/hacs/base.py
  custom_components/hacs/config_flow.py
  custom_components/hacs/utils/configuration_schema.py
  tests/test_config_flow.py
Labels: pr: refactor

#3860 Remove debug option
  custom_components/hacs/base.py
  custom_components/hacs/config_flow.py
  custom_components/hacs/utils/configuration_schema.py
  tests/test_config_flow.py
Labels: pr: refactor

#3866 Simplify progress_task logic
  custom_components/hacs/config_flow.py
Labels: pr: refactor

#3881 Bump frontend to 20240710163721
  scripts/install/frontend
Labels: pr: dependency-update

#3886 Add handler to get releases over grpahql
  custom_components/hacs/repositories/base.py
  custom_components/hacs/utils/github_graphql_query.py
  custom_components/hacs/websocket/__init__.py
  custom_components/hacs/websocket/repository.py
  tests/repositories/test_get_reposiotry_releases.py
  tests/snapshots/api-usage/tests/repositories/test_get_reposiotry_releasestest-get-reposiotry-releases-hacs-test-org-appdaemon-basic.json
  tests/snapshots/api-usage/tests/repositories/test_get_reposiotry_releasestest-get-reposiotry-releases-hacs-test-org-integration-basic.json
  tests/snapshots/api-usage/tests/repositories/test_get_reposiotry_releasestest-get-reposiotry-releases-hacs-test-org-plugin-basic.json
  tests/snapshots/api-usage/tests/repositories/test_get_reposiotry_releasestest-get-reposiotry-releases-hacs-test-org-python-script-basic.json
  tests/snapshots/api-usage/tests/repositories/test_get_reposiotry_releasestest-get-reposiotry-releases-hacs-test-org-template-basic.json
  tests/snapshots/api-usage/tests/repositories/test_get_reposiotry_releasestest-get-reposiotry-releases-hacs-test-org-theme-basic.json
  tests/snapshots/hacs-test-org/appdaemon-basic/test_get_reposiotry_releases.json
  tests/snapshots/hacs-test-org/integration-basic/test_get_reposiotry_releases.json
  tests/snapshots/hacs-test-org/plugin-basic/test_get_reposiotry_releases.json
  tests/snapshots/hacs-test-org/python_script-basic/test_get_reposiotry_releases.json
  tests/snapshots/hacs-test-org/template-basic/test_get_reposiotry_releases.json
  tests/snapshots/hacs-test-org/theme-basic/test_get_reposiotry_releases.json
  tests/snapshots/test_integration_setup.json
Labels: pr: enhancement

#3901 Bump frontend to 20240719084307
  scripts/install/frontend
Labels: pr: dependency-update

#3887 Use the same download handler for entity and websocket
  custom_components/hacs/repositories/base.py
  custom_components/hacs/update.py
  custom_components/hacs/websocket/repository.py
  tests/snapshots/api-usage/tests/repositories/test_update_repositorytest-update-repository-websocket-hacs-test-org-appdaemon-basic.json
  tests/snapshots/api-usage/tests/repositories/test_update_repositorytest-update-repository-websocket-hacs-test-org-integration-basic.json
  tests/snapshots/api-usage/tests/repositories/test_update_repositorytest-update-repository-websocket-hacs-test-org-plugin-basic.json
  tests/snapshots/api-usage/tests/repositories/test_update_repositorytest-update-repository-websocket-hacs-test-org-python-script-basic.json
  tests/snapshots/api-usage/tests/repositories/test_update_repositorytest-update-repository-websocket-hacs-test-org-template-basic.json
  tests/snapshots/api-usage/tests/repositories/test_update_repositorytest-update-repository-websocket-hacs-test-org-theme-basic.json
  tests/snapshots/hacs-test-org/appdaemon-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/integration-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/plugin-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/python_script-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/template-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/theme-basic/test_update_repository_websocket.json
Labels: pr: refactor

#3903 Add handler to use raw URL for manifest.json in validation
  custom_components/hacs/repositories/integration.py
  custom_components/hacs/validate/integration_manifest.py
  tests/action/test_hacs_action_integration.py
  tests/snapshots/action/test_hacs_action_integration/bad_documentation.log
  tests/snapshots/action/test_hacs_action_integration/bad_issue_tracker.log
  tests/snapshots/action/test_hacs_action_integration/valid_manifest1.log
  tests/snapshots/api-usage/tests/action/test_hacs_action_integrationtest-hacs-action-integration-bad-documentation-manifest0-false.json
  tests/snapshots/api-usage/tests/action/test_hacs_action_integrationtest-hacs-action-integration-bad-issue-tracker-manifest1-false.json
  tests/snapshots/api-usage/tests/action/test_hacs_action_integrationtest-hacs-action-integration-valid-manifest1-manifest2-true.json
  tests/validate/test_integration_manifest_check.py
Labels: pr: new-feature

#3918 Ignore created/modified-at timestamps in snapshot
  tests/conftest.py
Labels: pr: test

#3917 Add prerelease to repository data
  custom_components/hacs/repositories/base.py
  custom_components/hacs/utils/data.py
  custom_components/hacs/utils/validate.py
  tests/snapshots/diagnostics/base.json
  tests/snapshots/diagnostics/exception.json
  tests/utils/test_validate.py
Labels: pr: new-feature

#3930 Bump frontend to 20240729171855
  scripts/install/frontend
Labels: pr: dependency-update
