Repository hacs/integration, pull requests merged in 2024-09, with the labels that each got.

#4024 Show all pending updates
  custom_components/hacs/repositories/base.py
  tests/repositories/test_display_status.py
  tests/snapshots/api-usage/tests/repositories/test_display_statustest-display-status.json
Labels: pr: bugfix

#4025 Include the full diff in the artifact upload
  .github/workflows/generate-hacs-data.yml
  .github/workflows/validate.yml
Labels: pr: repository

#4032 Bump frontend to 20240903140523
  scripts/install/frontend
Labels: pr: dependency-update

#4033 Output the current stored data in action
  scripts/data/generate_category_data.py
Labels: pr: repository

#4035 Speed up action container
  .dockerignore
  action/Dockerfile
  scripts/install/uv_packages
Labels: pr: action

#4034 Dump known data in the action
  action/action.py
Labels: pr: action

#4036 Add frontend updates to the release notes
  .github/release.yml
Labels: pr: repository

#4037 Require HACS to be present
  scripts/data/validate_category_data.py
Labels: pr: action

#4038 Add log for diffTarget
  .github/workflows/generate-hacs-data.yml
Labels: pr: action

#4042 Update documentation link in manifest
  custom_components/hacs/manifest.json
Labels: pr: bugfix

#4052 Add devcontainer features to dependabot
  .github/dependabot.yml
Labels: pr: dependency-update

#4063 Bump requirements used in the action
  requirements_action.txt
Labels: pr: action

#4093 Adjust string to fix hassfest error
  custom_components/hacs/translations/en.json
Labels: pr: bugfix

#4094 Update and move HA test fixtures
  tests/common.py
  tests/conftest.py
  tests/homeassistantfixtures/__init__.py
  tests/homeassistantfixtures/common.py
  tests/homeassistantfixtures/dev.py
  tests/homeassistantfixtures/min.py
  tests/test_diagnostics.py
Labels: pr: test
