Repository hacs/integration, pull requests merged in 2024-06, with the labels that each got.

#3755 Show more errors in the generator logs
  custom_components/hacs/repositories/base.py
Labels: pr: refactor

#3757 Include dashboard resources in HACS data snapshots
  tests/conftest.py
  tests/snapshots/hacs-test-org/appdaemon-basic/test_discard_invalid_repo_data.json
  tests/snapshots/hacs-test-org/appdaemon-basic/test_download_repository.json
  tests/snapshots/hacs-test-org/appdaemon-basic/test_remove_repository_post.json
  tests/snapshots/hacs-test-org/appdaemon-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/appdaemon-basic/test_update_repository_entity.json
  tests/snapshots/hacs-test-org/appdaemon-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/integration-basic/test_discard_invalid_repo_data.json
  tests/snapshots/hacs-test-org/integration-basic/test_download_repository.json
  tests/snapshots/hacs-test-org/integration-basic/test_remove_repository_post.json
  tests/snapshots/hacs-test-org/integration-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/integration-basic/test_update_repository_entity.json
  tests/snapshots/hacs-test-org/integration-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/plugin-basic/test_discard_invalid_repo_data.json
  tests/snapshots/hacs-test-org/plugin-basic/test_download_repository.json
  tests/snapshots/hacs-test-org/plugin-basic/test_remove_repository_post.json
  tests/snapshots/hacs-test-org/plugin-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/plugin-basic/test_update_repository_entity.json
  tests/snapshots/hacs-test-org/plugin-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/python_script-basic/test_discard_invalid_repo_data.json
  tests/snapshots/hacs-test-org/python_script-basic/test_download_repository.json
  tests/snapshots/hacs-test-org/python_script-basic/test_remove_repository_post.json
  tests/snapshots/hacs-test-org/python_script-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/python_script-basic/test_update_repository_entity.json
  tests/snapshots/hacs-test-org/python_script-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/template-basic/test_discard_invalid_repo_data.json
  tests/snapshots/hacs-test-org/template-basic/test_download_repository.json
  tests/snapshots/hacs-test-org/template-basic/test_remove_repository_post.json
  tests/snapshots/hacs-test-org/template-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/template-basic/test_update_repository_entity.json
  tests/snapshots/hacs-test-org/template-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/theme-basic/test_discard_invalid_repo_data.json
  tests/snapshots/hacs-test-org/theme-basic/test_download_repository.json
  tests/snapshots/hacs-test-org/theme-basic/test_remove_repository_post.json
  tests/snapshots/hacs-test-org/theme-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/theme-basic/test_update_repository_entity.json
  tests/snapshots/hacs-test-org/theme-basic/test_update_repository_websocket.json
  tests/snapshots/test_integration_setup.json
  tests/snapshots/test_integration_setup_with_custom_updater.json
Labels: pr: test

#3760 Run unzip and remove directory jobs in executors
  custom_components/hacs/repositories/base.py
  custom_components/hacs/utils/file_system.py
  tests/utils/test_fs_util.py
Labels: pr: bugfix

#3759 Implement async_uninstall_removal for repositories
  custom_components/hacs/repositories/base.py
  custom_components/hacs/repositories/integration.py
  custom_components/hacs/repositories/template.py
  custom_components/hacs/repositories/theme.py
Labels: pr: refactor

#3758 Add and update dashboard resources
  custom_components/hacs/repositories/plugin.py
  tests/conftest.py
  tests/output/proxy_calls.json
  tests/repositories/test_plugin_repository.py
  tests/repositories/test_remove_repository.py
  tests/snapshots/hacs-test-org/plugin-basic/test_download_repository.json
  tests/snapshots/hacs-test-org/plugin-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/plugin-basic/test_update_repository_entity.json
  tests/snapshots/hacs-test-org/plugin-basic/test_update_repository_websocket.json
Labels: pr: new-feature

#3762 Ignore warning in tests for web.AppKey
  pyproject.toml
Labels: pr: test

#3784 Remove custom event loop fixture
  tests/conftest.py
Labels: pr: test

#3778 Install the frontend wheel from GitHub
  scripts/install/frontend
Labels: pr: repository

#3794 Add issue template for add-ons
  .github/ISSUE_TEMPLATE/f_addon.yml
Labels: pr: repository

#3796 Bump frontend to 20240620075826
  scripts/install/frontend
Labels: pr: dependency-update

#3798 Store experimental key in config entry options
  custom_components/hacs/config_flow.py
  tests/snapshots/config_flow/test_full_user_flow_implementation.json
  tests/test_config_flow.py
Labels: pr: refactor

#3799 Load repositories from hacs.repositories
  custom_components/hacs/utils/data.py
Labels: pr: bugfix

#3806 Add diff to validate output
  .github/workflows/validate.yml
Labels: pr: repository

#3814 Add summarize job to data generator
  .github/workflows/generate-hacs-data.yml
Labels: pr: repository

#3816 Always upload artifacts
  .github/workflows/generate-hacs-data.yml
Labels: pr: repository

#3817 Always generate summary
  scripts/data/generate_category_data.py
Labels: pr: repository

#3818 Add publish job to generate and move cache bust there
  .github/workflows/generate-hacs-data.yml
Labels: pr: repository

#3819 Move notification to the end of all jobs
  .github/workflows/generate-hacs-data.yml
Labels: pr: repository

#3820 Use vars in action
  .github/workflows/generate-hacs-data.yml
Labels: pr: repository

#3821 Create individual dynamic publish environments
  .github/workflows/generate-hacs-data.yml
Labels: pr: repository

#3823 Add validation to publish
  .github/workflows/generate-hacs-data.yml
Labels: pr: repository

#3824 Verify for diff changes
  .github/workflows/generate-hacs-data.yml
Labels: pr: repository

#3826 Move R2 upload step
  .github/workflows/generate-hacs-data.yml
Labels: pr: repository

#3827 Always write the content
  .github/workflows/generate-hacs-data.yml
  scripts/data/generate_category_data.py
Labels: pr: repository

#3829 Dynamic changedPct target
  .github/workflows/generate-hacs-data.yml
Labels: pr: repository

#3831 Add graphql limits to summary
  scripts/data/generate_category_data.py
  tests/scripts/data/test_generate_category_data.py
  tests/snapshots/scripts/data/generate_category_data/appdaemon/summary.json
  tests/snapshots/scripts/data/generate_category_data/integration/summary.json
  tests/snapshots/scripts/data/generate_category_data/plugin/summary.json
  tests/snapshots/scripts/data/generate_category_data/python_script/summary.json
  tests/snapshots/scripts/data/generate_category_data/single/appdaemon/hacs-test-org/appdaemon-basic/summary.json
  tests/snapshots/scripts/data/generate_category_data/single/integration/hacs-test-org/integration-basic/summary.json
  tests/snapshots/scripts/data/generate_category_data/single/plugin/hacs-test-org/plugin-basic/summary.json
  tests/snapshots/scripts/data/generate_category_data/single/python_script/hacs-test-org/python_script-basic/summary.json
  tests/snapshots/scripts/data/generate_category_data/single/template/hacs-test-org/template-basic/summary.json
  tests/snapshots/scripts/data/generate_category_data/single/theme/hacs-test-org/theme-basic/summary.json
  tests/snapshots/scripts/data/generate_category_data/template/summary.json
  tests/snapshots/scripts/data/generate_category_data/theme/summary.json
Labels: pr: repository
