Repository hacs/integration, pull requests merged in 2024-04, with the labels that each got.

#3583 Use Python 3.12 for testing against core dev
  .github/workflows/pytest.yml
  tests/common.py
Labels: pr: refactor

#3566 Add HacsBase.__init__
  custom_components/hacs/base.py
Labels: pr: refactor

#3601 Add more expected labels
  .github/workflows/pull_requests_labels.yml
Labels: pr: action

#3598 Use get_hacs helper in config_flow test
  tests/test_config_flow.py
Labels: pr: test

#3600 Move if statement to step
  .github/workflows/validate.yml
Labels: pr: action

#3602 Bump ludeeus/action-require-labels from 1.0.0 to 1.1.0
  .github/workflows/pull_requests_labels.yml
Labels: pr: action

#3604 Add system health tests
  tests/output/proxy_calls.json
  tests/snapshots/system_health/system_health.json
  tests/test_system_health.py
Labels: pr: test

#3605 Handle unloaded config entry in system_health_info
  custom_components/hacs/system_health.py
  tests/snapshots/system_health/system_health_after_unload.json
  tests/test_system_health.py
Labels: pr: refactor

#3603 Avoid creating two HacsBase instances when setup via config entry
  custom_components/hacs/__init__.py
Labels: pr: refactor

#3606 Remove final write listener on config entry unload
  custom_components/hacs/base.py
Labels: pr: refactor

#3607 Trigger PR label check on open and synchronize
  .github/workflows/pull_requests_labels.yml
Labels: pr: action

#3599 Use freezegun in tests and add last_fetched to snapshots
  requirements_test.txt
  tests/common.py
  tests/conftest.py
  tests/patch_time.py
  tests/snapshots/hacs-test-org/appdaemon-basic/test_download_repository.json
  tests/snapshots/hacs-test-org/appdaemon-basic/test_remove_repository_post.json
  tests/snapshots/hacs-test-org/appdaemon-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/appdaemon-basic/test_update_repository_entity.json
  tests/snapshots/hacs-test-org/appdaemon-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/integration-basic/test_download_repository.json
  tests/snapshots/hacs-test-org/integration-basic/test_remove_repository_post.json
  tests/snapshots/hacs-test-org/integration-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/integration-basic/test_update_repository_entity.json
  tests/snapshots/hacs-test-org/integration-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/plugin-basic/test_download_repository.json
  tests/snapshots/hacs-test-org/plugin-basic/test_remove_repository_post.json
  tests/snapshots/hacs-test-org/plugin-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/plugin-basic/test_update_repository_entity.json
  tests/snapshots/hacs-test-org/plugin-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/python_script-basic/test_download_repository.json
  tests/snapshots/hacs-test-org/python_script-basic/test_remove_repository_post.json
  tests/snapshots/hacs-test-org/python_script-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/python_script-basic/test_update_repository_entity.json
  tests/snapshots/hacs-test-org/python_script-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/template-basic/test_download_repository.json
  tests/snapshots/hacs-test-org/template-basic/test_remove_repository_post.json
  tests/snapshots/hacs-test-org/template-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/template-basic/test_update_repository_entity.json
  tests/snapshots/hacs-test-org/template-basic/test_update_repository_websocket.json
  tests/snapshots/hacs-test-org/theme-basic/test_download_repository.json
  tests/snapshots/hacs-test-org/theme-basic/test_remove_repository_post.json
  tests/snapshots/hacs-test-org/theme-basic/test_remove_repository_pre.json
  tests/snapshots/hacs-test-org/theme-basic/test_update_repository_entity.json
  tests/snapshots/hacs-test-org/theme-basic/test_update_repository_websocket.json
  tests/snapshots/test_integration_setup.json
Labels: pr: test

#3573 Fix a few typos
  custom_components/hacs/__init__.py
  custom_components/hacs/base.py
  custom_components/hacs/repositories/__init__.py
  custom_components/hacs/websocket/repositories.py
Labels: pr: refactor

#3597 Remove useless assignments
  custom_components/hacs/repositories/base.py
Labels: pr: refactor

#3592 Bump codespell version used by pre-commit
  .github/pre-commit-config.yaml
Labels: pr: dependency-update

#3608 Replace deprecated hass.helpers usage
  custom_components/hacs/base.py
Labels: pr: refactor

#3610 Sync async_test_home_assistant with core
  tests/common.py
Labels: pr: test

#3611 Adjust pytest configuration
  .github/workflows/pytest.yml
  pyproject.toml
  scripts/test
Labels: pr: test

#3612 Fix startup race
  custom_components/hacs/__init__.py
Labels: pr: bugfix

#3613 Replace devcontainer image
  .devcontainer.json
Labels: pr: repository

#3526 Throw error on wrong category
  action/action.py
Labels: pr: bugfix

#3586 Tweak check for custom_updater custom integration
  custom_components/hacs/__init__.py
  tests/integration/test_integration_setup.py
  tests/snapshots/test_integration_setup_with_custom_updater.json
Labels: pr: refactor

#3614 Run black on the action as well
  .github/pre-commit-config.yaml
  action/action.py
Labels: pr: repository

#3615 Add isort to CI
  .github/workflows/lint.yaml
  custom_components/hacs/repositories/base.py
  custom_components/hacs/utils/data.py
  tests/test_system_health.py
Labels: pr: repository

#3617 Small typing tweaks to websocket API
  custom_components/hacs/websocket/__init__.py
  custom_components/hacs/websocket/critical.py
  custom_components/hacs/websocket/repositories.py
  custom_components/hacs/websocket/repository.py
Labels: pr: refactor

#3619 Small typing tweaks to validators
  custom_components/hacs/validate/archived.py
  custom_components/hacs/validate/base.py
  custom_components/hacs/validate/brands.py
  custom_components/hacs/validate/description.py
  custom_components/hacs/validate/hacsjson.py
  custom_components/hacs/validate/images.py
  custom_components/hacs/validate/information.py
  custom_components/hacs/validate/integration_manifest.py
  custom_components/hacs/validate/issues.py
  custom_components/hacs/validate/manager.py
  custom_components/hacs/validate/topics.py
Labels: pr: refactor

#3567 Fix spelling of HacsBase.async_process_queue
  custom_components/hacs/base.py
  tests/hacsbase/test_hacs.py
Labels: pr: refactor

#3620 Bump actions/setup-python to 5.1.0
  .github/workflows/generate-hacs-data.yml
  .github/workflows/lint.yaml
  .github/workflows/publish.yml
  .github/workflows/pytest.yml
  .github/workflows/validate.yml
Labels: pr: dependency-update

#3621 Remove CodeQL workflow file
  .github/workflows/codeql-analysis.yml
Labels: pr: action

#3577 Correct codespell arguments
  .github/pre-commit-config.yaml
Labels: pr: repository

#3631 Use the "local" repo for precommit to reused installed versions of requirements
  .github/pre-commit-config.yaml
  .github/workflows/lint.yaml
  requirements_lint.txt
Labels: pr: repository

#3629 Remove bellybutton configuration
  .bellybutton.yml
Labels: pr: repository

#3628 Bump Pillow test dependency
  requirements_test.txt
Labels: pr: dependency-update

#3630 Bump black target version to Python 3.11
  pyproject.toml
Labels: pr: repository

#3634 Install pre-commit as part of setup
  scripts/setup
Labels: pr: repository

#3627 Set a stricter version of home-assistant to use in tests
  .github/workflows/lint.yaml
  .github/workflows/pytest.yml
  requirements_base.txt
  requirements_core_min.txt
  requirements_generate_data.txt
  requirements_lint.txt
  requirements_test.txt
  scripts/install/core
  scripts/install/core_dev
  scripts/setup
Labels: pr: test

#3618 Add basic tests of update entity
  tests/conftest.py
  tests/output/proxy_calls.json
  tests/snapshots/hacs-test-org/appdaemon-basic/test_update_entity_state.json
  tests/snapshots/hacs-test-org/integration-basic/test_update_entity_state.json
  tests/snapshots/hacs-test-org/plugin-basic/test_update_entity_state.json
  tests/snapshots/hacs-test-org/python_script-basic/test_update_entity_state.json
  tests/snapshots/hacs-test-org/template-basic/test_update_entity_state.json
  tests/snapshots/hacs-test-org/theme-basic/test_update_entity_state.json
  tests/test_update.py
Labels: pr: test

#3641 Show diff when pre-commit fails
  .github/workflows/lint.yaml
Labels: pr: repository
